# Cleaning Team Data

This will clean up the "team.json" file for efficient use and fix indexing.

#### Import Packages

In [1]:
# Import packages
import pandas as pd
import numpy as np
import json
pd.set_option('display.max_columns', None)

#### Read file and convert to DataFrame

In [2]:
# Read teams json
with open('../../data/json/teams/teams.json', 'r') as f:
    teams_json = json.load(f)
    
# Convert json to dataframe
teams = pd.DataFrame(teams_json)

print(teams.shape)

(20, 23)

#### Clean up DataFrame
- Remove bloating columns

In [3]:
# Remove bloating columns
keep_columns = ['name', 'short_name', 'strength', 'strength_attack_home', 'strength_attack_away', 'strength_defence_home', 'strength_defence_away', 'strength_overall_home', 'strength_overall_away']
teams = teams[keep_columns]
teams.head(20)

,name,short_name,strength,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,strength_overall_home,strength_overall_away
0,Arsenal,ARS,4,1240,1270,1310,1340,1260,1320
1,Bournemouth,BOU,3,1040,1100,1120,1130,1030,1130
2,Brighton,BHA,2,1040,1140,1010,1070,1030,1050
3,Burnley,BUR,3,990,1030,1000,1040,1070,1100
4,Cardiff,CAR,2,1030,1060,1020,1090,1030,1080
5,Chelsea,CHE,4,1270,1340,1320,1330,1260,1310
6,Crystal Palace,CRY,2,1030,1180,1030,1050,1060,1080
7,Everton,EVE,3,1070,1120,1140,1230,1090,1110
8,Fulham,FUL,2,1000,1030,1000,1080,1000,1040
9,Huddersfield,HUD,2,1030,1060,990,1010,1010,1020
10,Leicester,LEI,3,1130,1180,1080,1140,1110,1110
11,Liverpool,LIV,5,1330,1360,1330,1340,1330,1350
12,Man City,MCI,5,1320,1330,1340,1360,1320,1350
13,Man Utd,MUN,4,1250,1260,1310,1340,1310,1330
14,Newcastle,NEW,3,1070,1110,1030,1050,1070,1120
15,Southampton,SOU,2,1040,1070,1100,1100,1050,1060
16,Spurs,TOT,5,1270,1340,1320,1340,1330,1330
17,Watford,WAT,3,1100,1100,1130,1150,1100,1110
18,West Ham,WHU,3,1090,1100,1120,1150,1100,1150
19,Wolves,WOL,3,1180,1200,1080,1100,1130,1150

#### Save as csv

In [4]:
teams.to_csv(r'../../data/csv/teams.csv', index_label=False, index=False)

In [5]:
print(teams.shape)

(20, 9)